-- MySQL Script generated by MySQL Workbench
-- Sáb 09 Jan 2016 16:38:19 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tab_producing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_producing` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `income` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_building` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `level` INT NOT NULL COMMENT '',
  `title` VARCHAR(100) NOT NULL COMMENT '',
  `cost_wood` INT NOT NULL COMMENT '',
  `cost_stone` INT NOT NULL COMMENT '',
  `cost_iron` INT NOT NULL COMMENT '',
  `destruction_cost` INT NOT NULL COMMENT '',
  `build_time` INT NOT NULL COMMENT '',
  `destruction_time` INT(11) NOT NULL COMMENT '',
  `rank_point` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Tab_building_Tab_producing1_idx` (`level` ASC)  COMMENT '',
  CONSTRAINT `fk_Tab_building_Tab_producing1`
    FOREIGN KEY (`level`)
    REFERENCES `mydb`.`Tab_producing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_resources` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  `bonus_amout` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_mapper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_mapper` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `x` INT NOT NULL COMMENT '',
  `y` INT NOT NULL COMMENT '',
  `z` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_player` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nickname` VARCHAR(10) NOT NULL COMMENT '',
  `password` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_world`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_world` (
  `id` INT NOT NULL COMMENT '',
  `id_player` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Tab_world_Tab_player1_idx` (`id_player` ASC)  COMMENT '',
  CONSTRAINT `fk_Tab_world_Tab_player1`
    FOREIGN KEY (`id_player`)
    REFERENCES `mydb`.`Tab_player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_city` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_mapper` INT NOT NULL COMMENT '',
  `id_world` INT NOT NULL COMMENT '',
  `id_player` INT NOT NULL COMMENT '',
  `city_name` VARCHAR(45) NOT NULL COMMENT '',
  `total_points` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_City_Tab_mapper1_idx` (`id_mapper` ASC)  COMMENT '',
  INDEX `fk_Tab_city_Tab_world1_idx` (`id_world` ASC)  COMMENT '',
  INDEX `fk_Tab_city_Tab_player1_idx` (`id_player` ASC)  COMMENT '',
  CONSTRAINT `fk_City_Tab_mapper1`
    FOREIGN KEY (`id_mapper`)
    REFERENCES `mydb`.`Tab_mapper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tab_city_Tab_world1`
    FOREIGN KEY (`id_world`)
    REFERENCES `mydb`.`Tab_world` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tab_city_Tab_player1`
    FOREIGN KEY (`id_player`)
    REFERENCES `mydb`.`Tab_player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_city_Tab_building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_city_Tab_building` (
  `id_city` INT NOT NULL COMMENT '',
  `id_building` INT NOT NULL COMMENT '',
  `id_mapper` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_city`, `id_building`, `id_mapper`)  COMMENT '',
  INDEX `fk_City_has_Tab_building_Tab_building1_idx` (`id_building` ASC)  COMMENT '',
  INDEX `fk_City_has_Tab_building_City1_idx` (`id_city` ASC)  COMMENT '',
  INDEX `fk_Tab_city_Tab_building_Tab_mapper1_idx` (`id_mapper` ASC)  COMMENT '',
  CONSTRAINT `fk_City_has_Tab_building_City1`
    FOREIGN KEY (`id_city`)
    REFERENCES `mydb`.`Tab_city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_City_has_Tab_building_Tab_building1`
    FOREIGN KEY (`id_building`)
    REFERENCES `mydb`.`Tab_building` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tab_city_Tab_building_Tab_mapper1`
    FOREIGN KEY (`id_mapper`)
    REFERENCES `mydb`.`Tab_mapper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_city_has_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_city_has_resources` (
  `id_city` INT NOT NULL COMMENT '',
  `id_resources` INT NOT NULL COMMENT '',
  `id_mapper` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_city`, `id_resources`, `id_mapper`)  COMMENT '',
  INDEX `fk_City_has_Tab_resources_Tab_resources1_idx` (`id_resources` ASC)  COMMENT '',
  INDEX `fk_City_has_Tab_resources_City1_idx` (`id_city` ASC)  COMMENT '',
  INDEX `fk_Tab_city_has_resources_Tab_mapper1_idx` (`id_mapper` ASC)  COMMENT '',
  CONSTRAINT `fk_City_has_Tab_resources_City1`
    FOREIGN KEY (`id_city`)
    REFERENCES `mydb`.`Tab_city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_City_has_Tab_resources_Tab_resources1`
    FOREIGN KEY (`id_resources`)
    REFERENCES `mydb`.`Tab_resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tab_city_has_resources_Tab_mapper1`
    FOREIGN KEY (`id_mapper`)
    REFERENCES `mydb`.`Tab_mapper` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_city_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_city_instance` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_city` INT NOT NULL COMMENT '',
  `amout_wood` INT NOT NULL COMMENT '',
  `amout_stone` INT NOT NULL COMMENT '',
  `amout_iron` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `id_city`)  COMMENT '',
  INDEX `fk_Tab_city_instance_Tab_city1_idx` (`id_city` ASC)  COMMENT '',
  CONSTRAINT `fk_Tab_city_instance_Tab_city1`
    FOREIGN KEY (`id_city`)
    REFERENCES `mydb`.`Tab_city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_event_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_event_type` (
  `id` INT NOT NULL COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_event` (
  `id` INT NOT NULL COMMENT '',
  `id_event_type` INT NOT NULL COMMENT '',
  `initialized` TIMESTAMP NOT NULL COMMENT '',
  `active` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Tab_event_Tab_event_type1_idx` (`id_event_type` ASC)  COMMENT '',
  CONSTRAINT `fk_Tab_event_Tab_event_type1`
    FOREIGN KEY (`id_event_type`)
    REFERENCES `mydb`.`Tab_event_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_bonus_building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_bonus_building` (
  `id` INT NOT NULL COMMENT '',
  `efficiency` INT NOT NULL COMMENT '',
  `storage` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_Tab_bonus_building_Tab_producing1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`Tab_producing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_building_requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_building_requirement` (
  `id_building` INT NOT NULL COMMENT '',
  `id_building_required` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_building`, `id_building_required`)  COMMENT '',
  INDEX `fk_Tab_building_requirement_Tab_building2_idx` (`id_building_required` ASC)  COMMENT '',
  CONSTRAINT `fk_Tab_building_requirement_Tab_building1`
    FOREIGN KEY (`id_building`)
    REFERENCES `mydb`.`Tab_building` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tab_building_requirement_Tab_building2`
    FOREIGN KEY (`id_building_required`)
    REFERENCES `mydb`.`Tab_building` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tab_storage_building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tab_storage_building` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `level` INT NOT NULL COMMENT '',
  `storage` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Tab_storage_building_Tab_producing1_idx` (`level` ASC)  COMMENT '',
  CONSTRAINT `fk_Tab_storage_building_Tab_producing1`
    FOREIGN KEY (`level`)
    REFERENCES `mydb`.`Tab_producing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
